spring:
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/employeemanagmentdb
    username: root
    password: Root1234*
    driverClassName: com.mysql.cj.jdbc.Driver